// flow-typed signature: 56676dae5f3e41c6caeb2d512614736e
// flow-typed version: <<STUB>>/css-hot-loader_v1.4.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-hot-loader/hotModuleReplacement' {
  declare module.exports: any;
}

declare module 'css-hot-loader/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-hot-loader/hotModuleReplacement.js' {
  declare module.exports: $Exports<'css-hot-loader/hotModuleReplacement'>;
}
declare module 'css-hot-loader/index' {
  declare module.exports: $Exports<'css-hot-loader'>;
}
declare module 'css-hot-loader/index.js' {
  declare module.exports: $Exports<'css-hot-loader'>;
}
declare module 'css-hot-loader/loader.js' {
  declare module.exports: $Exports<'css-hot-loader/loader'>;
}
